In [29]:
# task: return the learned embeddings for each token
from transformers import pipeline
from transformers import RobertaTokenizerFast
import torch

In [5]:
from transformers import AutoTokenizer, AutoModelForTokenClassification

In [13]:
PRETRAINED_MODEL = "../checkpoint-final/"
NUM_CLASSES = 2
TOKENIZER_PATH =  "../checkpoint-final/"
model = AutoModelForTokenClassification.from_pretrained(PRETRAINED_MODEL, num_labels=NUM_CLASSES)
tokenizer = RobertaTokenizerFast.from_pretrained(TOKENIZER_PATH, do_lower_case=False)
# model_pipeline = pipeline('feature-extraction', model=model, tokenizer=tokenizer)
# data = model_pipeline('AVA')

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [18]:
import random

# Define the 20 standard amino acids
amino_acids = "ACDEFGHIKLMNPQRSTVWY"

# Generate a random amino acid sequence of length 10
random_sequence = ''.join(random.choice(amino_acids) for _ in range(10))

print(random_sequence)

VSHQPPEDGL


In [19]:
##how the words are broken into tokens
print(tokenizer.tokenize(random_sequence))

['V', 'S', 'H', 'Q', 'P', 'P', 'E', 'D', 'G', 'L']


In [20]:
##the format of a encoding
print(tokenizer.batch_encode_plus([random_sequence]))

{'input_ids': [[4, 8, 10, 22, 18, 16, 16, 9, 14, 7, 5, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}


In [22]:
print(tokenizer.batch_encode_plus([random_sequence])['input_ids'])

[[4, 8, 10, 22, 18, 16, 16, 9, 14, 7, 5, 0]]


In [23]:
tokenizer.all_special_tokens

['<s>', '</s>', '[UNK]', '[SEP]', '[PAD]', '[CLS]', '[MASK]']

In [24]:
tokenizer.

<bound method SpecialTokensMixin.add_tokens of RobertaTokenizerFast(name_or_path='../checkpoint-final/', vocab_size=30, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=True), 'eos_token': AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True), 'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': AddedToken("[MASK]", rstrip=False, lstrip=True, single_word=False, normalized=False)}, clean_up_tokenization_spaces=True)>

In [74]:
random_sequence = 'VSHQPPEDGL'

In [63]:
input_ids = tokenizer.encode(random_sequence, return_tensors="pt")

In [64]:
input_ids

tensor([[4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0]])

In [65]:
# Get token embeddings
with torch.no_grad():
    outputs = model(input_ids, output_hidden_states=True)
    embeddings = outputs.hidden_states

In [67]:
embeddings[-1].shape

torch.Size([1, 13, 768])

In [72]:
embeddings[-1][0][1][:10]

tensor([ 0.1838,  0.4129, -0.2674,  0.3793,  0.1303,  0.3081, -0.2605, -0.5416,
        -0.3524, -1.4826])

In [73]:
embeddings[-1][0][2][:10]

tensor([-0.4745,  0.2408, -0.4009, -0.2871, -0.0784,  0.0486, -0.1656, -0.4000,
         0.2476, -1.2927])